
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
   branches:
  only:
  - develop
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coverage
